---
title: "seeds-Amani"
output: html_document
---

#Libraries
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(boot)
#function for table
html_table <- function(x, page_length = 5) {
  if (is.null(page_length)) {
    return(DT::datatable(
    data = x, 
    rownames = FALSE, 
    options = list(
      dom = 't', 
      scrollX = TRUE, 
      pageLength = nrow(x)
    )
  ))
  }
  DT::datatable(
    data = x, 
    rownames = FALSE, 
    options = list(
      dom = 'tip', 
      scrollX = TRUE, 
      pageLength = page_length
    )
  )
}
```


## Data & Init


```{r cars}
alpha0 <- 0
alpha1 <- 0
alpha2 <- 0
alpha12 <- 0
tau <- 10
b <- c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0)
"N" <- 
21
"r" <-
c(10, 23, 23, 26, 17, 5, 53, 55, 32, 46, 10, 8, 10, 8, 23, 0, 
3, 22, 15, 32, 3)
"n" <-
c(39, 62, 81, 51, 39, 6, 74, 72, 51, 79, 13, 16, 30, 28, 45, 
4, 12, 41, 30, 51, 7)
"x1" <-
c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1)
"x2" <-
c(0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 
1)
```

## Function : Gibbs's sampling


```{r pressure, echo=FALSE}

gibbs_Seeds <- function(nchain , n , r , N , X1, X2 , prop_sd) {
  
  alpha0 <- 0
  alpha1 <- 0
  alpha2 <- 0
  alpha12 <- 0
  sigma2 <- 1/10
  b <- c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0)

  p = inv.logit(alpha0 + alpha1 * x1 + alpha2 * x2 + alpha12 * x1 * x2 + b)
  
  chain <- matrix(NA , nchain +1 , 5 )
  
  b_chain <- matrix(NA , nchain +1 , N )
  
  chain[1,] <- c(alpha0 , alpha1 , alpha2 , alpha12 , sigma2)
  
  b_chain[1,] <- b
  
  for (i in 1:nchain){
    
    # Mise a jour de alpha0
    
    prop <- rnorm(1, alpha0, prop_sd[1])
    
    prop_p <- inv.logit(prop + alpha1 * x1 + alpha2 * x2 + alpha12 * x1 * x2 + b)
    
    top <- prop * sum(r) + sum(n*log(1-prop_p)) - ((prop^2) / (2 * 1e6))
    
    bottom <- alpha0 * sum(r) + sum(n*log(1-p)) - ((alpha0^2) / (2 * 1e6))
    
    acc_prop = exp(top-bottom)
    
    if (runif(1) < acc_prop){
      alpha0 <- prop
      p <- prop_p
    }
    
    ## Mise a jour de alpha1
    
    prop <- rnorm(1, alpha1, prop_sd[2])
    
    prop_p <- inv.logit(alpha0 + prop * x1 + alpha2 * x2 + alpha12 * x1 * x2 + b)
    
    top <- prop * sum(r*x1) + sum(n*log(1-prop_p)) - ((prop^2) / (2 * 1e6))
    
    bottom <- alpha1 * sum(r*x1) + sum(n*log(1-p)) - ((alpha1^2) / (2 * 1e6))
    
    acc_prop = exp(top-bottom)
    
    
    if (runif(1) < acc_prop){
      alpha1 <- prop
      p <- prop_p
    }
    
        ## Mise a jour de alpha2
    
    prop <- rnorm(1, alpha2, prop_sd[3])
    
    prop_p <- inv.logit(alpha0 + alpha1 * x1 + prop * x2 + alpha12 * x1 * x2 + b)
    
    top <- prop * sum(r*x2) + sum(n*log(1-prop_p)) - ((prop^2) / (2 * 1e6))
    
    bottom <- alpha2 * sum(r*x2) + sum(n*log(1-p)) - ((alpha2^2) / (2 * 1e6))
    
    acc_prop = exp(top-bottom)
     

    if (runif(1) < acc_prop){
      alpha2 <- prop
      p <- prop_p
    }
    
        ## Mise a jour de alpha12
    
    prop <- rnorm(1, alpha12, prop_sd[4])
    
    prop_p <- inv.logit(alpha0 + alpha1 * x1 + alpha2 * x2 + prop * x1 * x2 + b)
    
    top <- prop * sum((r*x1)*x2) + sum(n*log(1-prop_p)) - ((prop^2) / (2 * 1e6))
    
    bottom <- alpha12 * sum((r*x1)*x2) + sum(n*log(1-p)) - ((alpha12^2) / (2 * 1e6))
    
    acc_prop = exp(top-bottom)
     

    if (runif(1) < acc_prop){
      alpha12 <- prop
      p <- prop_p
    }
    
            ## Mise a jour de b

    for (j in 1:N)
    {
      prop <- rnorm(1, b[j], prop_sd[5])
      prop_p_j <- inv.logit(alpha0 + alpha1 * x1[j] + alpha2 * x2[j] + alpha12 * x1[j] * x2[j] + prop)
      
      top <- - (prop^2 / (2 * sigma2)) + r[j] * log(prop_p_j) + (n[j] - r[j]) * log(1 - prop_p_j)
      bottom <- - (b[j]^2 / (2 * sigma2)) + r[j] * log(p[j]) + (n[j] - r[j]) * log(1 - p[j])
      
      acc_prob <- exp(top - bottom)
      if (!is.finite(acc_prob))
      browser()
      
      if (runif(1) < acc_prob){
        b[j] <- prop
        p[j] <- prop_p_j
      }
    }
    
        # Mise à jour de sigma2
    sigma2 <- 1 / rgamma(1, 10**(-3) + N / 2, 1/(10**(-3) + 0.5 * sum(b^2)))
    
    ## Mettre a jour ma chaine
    chain[i+1,] <- c(alpha0 , alpha1 , alpha2 , alpha12 , sigma2)
    b_chain[i+1,] <- b
  }
  return(chain)
  }
  
```

## Evaluating
```{r}
x <- gibbs_Seeds(10000 , n , r , N , x1, x2 , prop_sd = c(0.1,0.3,0.2,0.4,0.3))
summary(x)
```

```{r}
burnin <- 1:1000
plot(coda::mcmc(x[-burnin,]))
```

```{r}
sd_alpha0<- sd(x[-burnin,1])
sd_alpha1<- sd(x[-burnin,2])
sd_alpha2<- sd(x[-burnin,3])
sd_alpha12<-sd(x[-burnin,4])
sd_sigma <- sd(sqrt(x[,5]))

mean_alpha0 <- mean(x[-burnin,1])
mean_alpha1 <- mean(x[-burnin,2])
mean_alpha2 <- mean(x[-burnin,3])
mean_alpha12 <- mean(x[-burnin,4])
mean_sigma <- mean(sqrt(x[-burnin,5]))
  
```

```{r}
Results <- data_frame("parametres" = c("alpah0","alpha1","alpha2","alpha12","sigma"),"mean" = c(mean_alpha0,mean_alpha1,mean_alpha2,mean_alpha12,mean_sigma), "sd" = c(sd_alpha0,sd_alpha1,sd_alpha2,sd_alpha12,sd_sigma))
```

```{r}
Results %>%
  html_table()
```





Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
