---
title: "Seeds"
author: "Aya AMENSSAG"
date: "3/16/2022"
output: html_document
---
# Préparation des données :
```{r}
"N" <- 21
"r" <- c(10, 23, 23, 26, 17, 5, 53, 55, 32, 46, 10, 8, 10, 8, 23, 0, 3, 22, 15, 32, 3)
"n" <- c(39, 62, 81, 51, 39, 6, 74, 72, 51, 79, 13, 16, 30, 28, 45,  4, 12, 41, 30, 51, 7)
"x1" <- c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)
"x2" <- c(0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1)
```

# Initialisation :
```{r}
init_alpha0 <- 0
init_alpha1 <- 0
init_alpha2 <- 0
init_alpha12 <- 0
init_sigma <- 1/10
init_b <- c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
```

# Importation des packages:
```{r}
library(boot)
library(coda)
```

# Échantillonneur Hastings-within-Gibbs : 
```{r}
seeds <- function(nchain, init_alpha0, init_alpha1, init_alpha2, init_alpha12, init_sigma, init_b, prop_sd, x1, x2, N)
{
  
  alpha0 <- init_alpha0
  alpha1 <- init_alpha1
  alpha2 <- init_alpha2
  alpha12 <- init_alpha12
  sigma <- init_sigma
  b <- init_b
  
  p <- plogis(alpha0 + alpha1 * x1 + alpha2 * x2 + alpha12 * x1 * x2 + b)
  
  chain <- matrix(NA, nchain + 1, 5)
  chain_b <- matrix(NA, nchain + 1, N)
  
  chain[1,1] <- init_alpha0
  chain[1,2] <- init_alpha1
  chain[1,3] <- init_alpha2
  chain[1,4] <- init_alpha12
  chain[1,5] <- init_sigma
  chain_b[1,] <- init_b
  
  acc_rates <- rep(0,4)
  
  for (i in 1:nchain)
  {
    # Mise à jour de alpha0
    prop <- rnorm(1, alpha0, prop_sd[1])
    prop_p <- plogis(prop + alpha1 * x1 + alpha2 * x2 + alpha12 * x1 * x2 + b)
    
    top <- - ((prop^2) / (2 * 1e6)) + sum(r * log(prop_p)) + sum((n-r) * log(1 - prop_p))
    bottom <- - ((alpha0^2) / (2 * 1e6)) + sum(r * log(p)) + sum((n-r) * log(1 - p))
    
    acc_prob <- exp(top - bottom)
    
    if (runif(1) < acc_prob){
      alpha0 <- prop
      p <- prop_p
      acc_rates[1] <- acc_rates[1]+1
    }
    
    # Mise à jour de alpha1
    prop <- rnorm(1, alpha1, prop_sd[2])
    prop_p <- plogis(alpha0 + prop * x1 + alpha2 * x2 + alpha12 * x1 * x2 + b)
    
    top <- - ((prop^2) / (2 * 1e6)) + sum(r * log(prop_p)) + sum((n-r) * log(1 - prop_p))
    bottom <- - ((alpha1^2) / (2 * 1e6)) + sum(r * log(p)) + sum((n-r) * log(1 - p))
    
    acc_prob <- exp(top - bottom)
    
    if (runif(1) < acc_prob){
      alpha1 <- prop
      p <- prop_p
      acc_rates[2] <- acc_rates[2]+1
    }
    
    # Mise à jour de alpha2
    prop <- rnorm(1, alpha2, prop_sd[3])
    prop_p <- plogis(alpha0 + alpha1 * x1 + prop * x2 + alpha12 * x1 * x2 + b)
    
    top <- - ((prop^2) / (2 * 1e6)) + sum(r * log(prop_p)) + sum((n-r) * log(1 - prop_p))
    bottom <- - ((alpha2^2) / (2 * 1e6)) + sum(r * log(p)) + sum((n-r) * log(1 - p))
    
    acc_prob <- exp(top - bottom)
    
    if (runif(1) < acc_prob){
      alpha2 <- prop
      p <- prop_p
      acc_rates[3] <- acc_rates[3]+1
    }
    
    # Mise à jour de alpha12
    prop <- rnorm(1, alpha12, prop_sd[4])
    prop_p <- plogis(alpha0 + alpha1 * x1 + alpha2 * x2 + prop * x1 * x2 + b)
    
    top <- - ((prop^2) / (2 * 1e6)) + sum(r * log(prop_p)) + sum((n-r) * log(1 - prop_p))
    bottom <- - ((alpha12^2) / (2 * 1e6)) + sum(r * log(p)) + sum((n-r) * log(1 - p))
    
    acc_prob <- exp(top - bottom)

    if (runif(1) < acc_prob){
      alpha12 <- prop
      p <- prop_p
      acc_rates[4] <- acc_rates[4]+1
    }
    
    # Mise à jour de sigma
    sigma <- 1 / rgamma(1, shape = 10e-3 + N / 2, scale = 1e-3 + 0.5 * sum(b^2)) #change parameters
    
    # Mise à jour de b
    for (j in 1:N)
    {
      prop <- rnorm(1, b[j], prop_sd[5])
      prop_p_j <- plogis(alpha0 + alpha1 * x1[j] + alpha2 * x2[j] + alpha12 * x1[j] * x2[j] + prop)
      
      top <- - (prop^2 / (2 * sigma)) + r[j] * log(prop_p_j) + (n[j] - r[j]) * log(1 - prop_p_j)
      bottom <- - (b[j]^2 / (2 * sigma)) + r[j] * log(p[j]) + (n[j] - r[j]) * log(1 - p[j])
      
      acc_prob <- exp(top - bottom)
      
      if (runif(1) < acc_prob){
        b[j] <- prop
        p[j] <- prop_p_j
      }
    }
    #Mise à jour de la chaine
    chain[i+1,] <- c(alpha0, alpha1, alpha2, alpha12, sigma)
    chain_b[i+1,] <- b
  }
  my_list <- list("chain" = chain, "b_chain" = chain_b, "acc_rates" = acc_rates)
  return(my_list)
}
```


```{r}
l <- seeds(1e4, init_alpha0, init_alpha1, init_alpha2, init_alpha12, init_sigma, init_b, prop_sd = c(0.25, 0.65, 0.2, 0.3, 0.3), x1, x2, N)
```

# Résultat :

## $\alpha_0$
```{r}
burnin <- 1:1000 # On enlève les 1000 premières itérations (burn-in period)
plot(l$chain[-c(burnin),][,1], type = "l", main = "",ylab=text)
plot(density(l$chain[-c(burnin),][,1]), type = "l", main = "densité de alpha0")
    
```

```{r}
sprintf("Le taux d'acceptation de alpha0 : %s", l$acc_rates[1]/100)
sprintf("La moyenne empirique de alpha0 : %s", mean(l$chain[,1]))
sprintf("L'écart-type empirique de alpha0 : %s", sd(l$chain[,1]))
```

## $\alpha_1$
```{r}
plot(l$chain[-c(burnin),][,2], type = "l", main = "",ylab=text)
plot(density(l$chain[-c(burnin),][,2]), type = "l", main = "densité de alpha1")
```

```{r}
sprintf("Le taux d'acceptation de alpha1 : %s", l$acc_rates[2]/100)
sprintf("La moyenne empirique de alpha1 : %s", mean(l$chain[,2]))
sprintf("L'écart-type empirique de alpha1 : %s", sd(l$chain[,2]))
```

## $\alpha_2$
```{r}
plot(l$chain[-c(burnin),][,3], type = "l", main = "",ylab=text)
plot(density(l$chain[-c(burnin),][,3]), type = "l", main = "densité de alpha2")
```

```{r}
sprintf("Le taux d'acceptation de alpha2 : %s", l$acc_rates[3]/100)
sprintf("La moyenne empirique de alpha2 : %s", mean(l$chain[,3]))
sprintf("L'écart-type empirique de alpha2 : %s", sd(l$chain[,3]))
```

## $\alpha_{12}$
```{r}
plot(l$chain[-c(burnin),][,4], type = "l", main = "",ylab=text)
plot(density(l$chain[-c(burnin),][,4]), type = "l", main = "densité de alpha12")
```

```{r}
sprintf("Le taux d'acceptation de alpha12 : %s", l$acc_rates[4]/100)
sprintf("La moyenne empirique de alpha12 : %s", mean(l$chain[,4]))
sprintf("L'écart-type empirique de alpha12 : %s", sd(l$chain[,4]))
```
## $\sigma$
```{r}
plot(l$chain[-c(burnin),][,5], type = "l", main = "",ylab=text)
plot(density(l$chain[-c(burnin),][,5]), type = "l", main = "densité de sigma")
```

```{r}
sprintf("La moyenne empirique de sigma : %s", mean(l$chain[,5]))
sprintf("L'écart-type empirique de sigma : %s", sd(l$chain[,5]))
```


## $b$
```{r}
plot(mcmc(l$b_chain[-burnin,][,20]))
```
```{r}
text=c("alpha0", "alpha1", "alpha2", "alpha12", "sigma")
par(mfrow = c(5, 2), mar = c(4, 5, 0.5, 0.5))
for (j in 1:5){
  plot(l$chain[-c(burnin, 2890),][,j], type = "l", main = "",ylab=text[j])
  plot(density(l$chain[-c(burnin, 2890),][,j]), type = "l", main = "")
}
```


